#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH/../

set -e

CMD_TO_RUN="make && make test && make doc && cp build/linux/zeroerr.hpp ./zeroerr.hpp"
if [ -f "/etc/wsl.conf" ]; then
    bash -c "$CMD_TO_RUN"
else
    wsl -- bash -c "$CMD_TO_RUN"
fi

git add zeroerr.hpp
