add_rules("mode.debug", "mode.release")
set_policy("check.auto_ignore_flags", false)
target("zeroerr")
    set_kind("static")
    set_languages("cxx14")
    add_cxxflags("/utf-8")
    add_files("src/*.cpp")
    add_includedirs("include", "extension")
    add_headerfiles("include/(**.h)", "extension/(**.h)")

target("zeroerr-test")
    set_kind("binary")
    set_languages("cxx14")
    add_cxxflags("/utf-8")
    add_deps("zeroerr")
    add_files("test/unit_test.cpp")
    add_includedirs("include", "extension")

